In [1]:
import numpy as np

### Batches
Implement `get_batches` to create batches of input and targets using `int_text`.  The batches should be a Numpy array with the shape `(number of batches, 2, batch size, sequence length)`. Each batch contains two elements:
- The first element is a single batch of **input** with the shape `[batch size, sequence length]`
- The second element is a single batch of **targets** with the shape `[batch size, sequence length]`

If you can't fill the last batch with enough data, drop the last batch.

For exmple, `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2)` would return a Numpy array of the following:
```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2], [ 7  8], [13 14]]
    # Batch of targets
    [[ 2  3], [ 8  9], [14 15]]
  ]

  # Second Batch
  [
    # Batch of Input
    [[ 3  4], [ 9 10], [15 16]]
    # Batch of targets
    [[ 4  5], [10 11], [16 17]]
  ]

  # Third Batch
  [
    # Batch of Input
    [[ 5  6], [11 12], [17 18]]
    # Batch of targets
    [[ 6  7], [12 13], [18  1]]
  ]
]
```

Notice that the last target value in the last batch is the first input value of the first batch. In this case, `1`. This is a common technique used when creating sequence batches, although it is rather unintuitive.

In [26]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    chars_batch = batch_size*seq_length
    num_batches = len(int_text)//chars_batch
    print(num_batches)
    
    arr = np.array(int_text)
    arr = arr[:num_batches*chars_batch]
    print(arr)
    print(arr.shape)
    
    arr_f = np.zeros((num_batches, 2, batch_size, seq_length))
        
    init = 0
    for bat in range(num_batches):
        for bindx in range(2):
            for bs in range(batch_size):
                if bat == num_batches-1 and bindx == 1 and bs == batch_size-1:
                    arr_f[bat, bindx, bs] = arr[init:init+seq_length]
                    arr_f[bat, bindx, bs, [-1]] = arr[0]
                else: 
                    arr_f[bat, bindx, bs] = arr[init:init+seq_length]
                    init += seq_length - 1
        
    print(arr_f)
    print(arr.shape)
    
    return None

print(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2))
print(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,\
                   25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], 3, 2))

3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(18,)
[[[[  1.   2.]
   [  2.   3.]
   [  3.   4.]]

  [[  4.   5.]
   [  5.   6.]
   [  6.   7.]]]


 [[[  7.   8.]
   [  8.   9.]
   [  9.  10.]]

  [[ 10.  11.]
   [ 11.  12.]
   [ 12.  13.]]]


 [[[ 13.  14.]
   [ 14.  15.]
   [ 15.  16.]]

  [[ 16.  17.]
   [ 17.  18.]
   [ 18.   1.]]]]
(18,)
None
5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30]
(30,)
[[[[  1.   2.]
   [  2.   3.]
   [  3.   4.]]

  [[  4.   5.]
   [  5.   6.]
   [  6.   7.]]]


 [[[  7.   8.]
   [  8.   9.]
   [  9.  10.]]

  [[ 10.  11.]
   [ 11.  12.]
   [ 12.  13.]]]


 [[[ 13.  14.]
   [ 14.  15.]
   [ 15.  16.]]

  [[ 16.  17.]
   [ 17.  18.]
   [ 18.  19.]]]


 [[[ 19.  20.]
   [ 20.  21.]
   [ 21.  22.]]

  [[ 22.  23.]
   [ 23.  24.]
   [ 24.  25.]]]


 [[[ 25.  26.]
   [ 26.  27.]
   [ 27.  28.]]

  [[ 28.  29.]
   [ 29.  30.]
   [ 30.   1.]]]]
(30,)
None


In [50]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    
    # determinar número de batches que se pueden tener
    chars_batch = batch_size*seq_length
    num_batches = len(int_text)//chars_batch
    
    print(num_batches)
    
    # colocar el listado de entrada en un array
    arr = np.array(int_text)
    # limitar valores de array al número de batches que tengo
    # --------------------------- error --------------------------------------------------
    arr = arr[:num_batches*chars_batch+1]
    # --------------------------- error --------------------------------------------------

    # hacer un array de arrays con los valores ordenados
    #batch_size*num_batches*2 para considerar que por cada batch hay dos (inputs y targets) y tener numeros de batch par
    # --------------------------- error --------------------------------------------------
    arr_tot = np.zeros((batch_size*num_batches*2, seq_length))
    # --------------------------- error --------------------------------------------------
    
    # colocar los valores desfasados en arr_tot como lista de arrays
    # y al ultimo array agregar como ultimo valor el primer valor de la lista
    init = 0
    for a in range(arr_tot.shape[0]):
        print("{} en {}".format(arr_tot[a], arr[init:init+seq_length]))
        arr_tot[a] = arr[init:init+seq_length]
        init += seq_length - 1
    arr_tot[-1][-1] = arr[0]
    
    # crear un array del tamaño requerido en el ejercicio
    batches = np.zeros((num_batches, 2, batch_size, seq_length))
    
    # asignar los arrays a su batch correspondiente
    init_btc = 0
    for btc in range(num_batches):
        for bindx in range(2):
            for bs in range(batch_size):
                batches[btc, bindx, bs] = arr_tot[init_btc+num_batches*2*bs]  
            # Valor para conocer en que batch de batch se va es decir de 0 a 5 (total 3 batches * 2)
            init_btc += 1 
    
    return batches

print(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2))
print(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,\
                   25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], 3, 4))
print(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 5))

3
[ 0.  0.] en [1 2]
[ 0.  0.] en [2 3]
[ 0.  0.] en [3 4]
[ 0.  0.] en [4 5]
[ 0.  0.] en [5 6]
[ 0.  0.] en [6 7]
[ 0.  0.] en [7 8]
[ 0.  0.] en [8 9]
[ 0.  0.] en [ 9 10]
[ 0.  0.] en [10 11]
[ 0.  0.] en [11 12]
[ 0.  0.] en [12 13]
[ 0.  0.] en [13 14]
[ 0.  0.] en [14 15]
[ 0.  0.] en [15 16]
[ 0.  0.] en [16 17]
[ 0.  0.] en [17 18]
[ 0.  0.] en [18 19]
[[[[  1.   2.]
   [  7.   8.]
   [ 13.  14.]]

  [[  2.   3.]
   [  8.   9.]
   [ 14.  15.]]]


 [[[  3.   4.]
   [  9.  10.]
   [ 15.  16.]]

  [[  4.   5.]
   [ 10.  11.]
   [ 16.  17.]]]


 [[[  5.   6.]
   [ 11.  12.]
   [ 17.  18.]]

  [[  6.   7.]
   [ 12.  13.]
   [ 18.   1.]]]]
2
[ 0.  0.  0.  0.] en [1 2 3 4]
[ 0.  0.  0.  0.] en [4 5 6 7]
[ 0.  0.  0.  0.] en [ 7  8  9 10]
[ 0.  0.  0.  0.] en [10 11 12 13]
[ 0.  0.  0.  0.] en [13 14 15 16]
[ 0.  0.  0.  0.] en [16 17 18 19]
[ 0.  0.  0.  0.] en [19 20 21 22]
[ 0.  0.  0.  0.] en [22 23 24 25]
[ 0.  0.  0.  0.] en [25]
[ 0.  0.  0.  0.] en []


ValueError: could not broadcast input array from shape (0) into shape (4)